export const product = [
  {
    id: "product1",
    url: "http://localhost:8001/photo/2_1.webp",
    detailUrl: "http://localhost:8001/photo/2.webp",
    detailUr2: "http://localhost:8001/photo/2_2.webp",
    detailUr3: "http://localhost:8001/photo/2_3.webp",
    detailUr4: "http://localhost:8001/photo/2_4.webp",
    shortTitle: "Fastrack",
    longTitle: "EDM Analog Watch - For Men 3166KM01",
    size: "32mm",
    mrp: 1746,
    cost: 3250,
    quantity: 1,
    description:
      "This is a genuine Fastrack product. The product comes with a standard manufacturer warranty of 2 Years ",
    discount: "45% OFF",
    tagline: "male",
  },
  {
    id: "product2",
    url: "http://localhost:8001/photo/1_1.jpg",
    detailUrl: "http://localhost:8001/photo/1_2.webp",
    detailUr2: "http://localhost:8001/photo/1_2.webp",
    detailUr3: "http://localhost:8001/photo/1_3.webp",
    detailUr4: "http://localhost:8001/photo/1_4.webp",
    shortTitle: "Fastrack",
    longTitle: "Analog Watch - For Men 3240SL02",
    size: "28mm",
    mrp: 2465,
    cost: 2900,
    quantity: 1,
    description:
      "5 ATM/50 m Water resistance. Leather Strap. Stainless steel back cover. High precision quartz analogue movement. ",
    discount: "15% OFF",
    tagline: "male",
  },
  {
    id: "product3",
    url: "http://localhost:8001/photo/3_1.webp",
    detailUrl: "http://localhost:8001/photo/3.webp",
    detailUr2: "http://localhost:8001/photo/3_2.webp",
    detailUr3: "http://localhost:8001/photo/3_3.webp",
    detailUr4: "http://localhost:8001/photo/3_4.webp",
    shortTitle: "Fastrack",
    longTitle: "Sports Analog Watch - For Men NN3099SM01",
    size: "36mm",
    mrp: 1288,
    cost: 2795,
    quantity: 1,
    description:
      "Sport the ultimate masculine look wearing this incredibly stylish Fastrack Sports Analog Watch with a pair of jeans and a casual shirt to impress your peers. ",
    discount: "53% OFF",
    tagline: "male",
  },
  {
    id: "product4",
    url: "http://localhost:8001/photo/4_1.webp",
    detailUrl: "http://localhost:8001/photo/4.webp",
    detailUr2: "http://localhost:8001/photo/4_2.webp",
    detailUr3: "http://localhost:8001/photo/4_3.webp",
    detailUr4: "http://localhost:8001/photo/4_4.webp",
    shortTitle: "Fastrack",
    longTitle: "Upgrades 2015 Analog Watch - For Men NP3117SL04",
    size: "40mm",
    mrp: 948,
    cost: 1795,
    quantity: 1,
    description:
      "ATM/30m Water resistance. Silicon strap. Stainless steel back cover. High precision quartz analogue movement. ",
    discount: "47% OFF",
    tagline: "male",
  },
  {
    id: "product5",
    url: "http://localhost:8001/photo/5_1.webp",
    detailUrl: "http://localhost:8001/photo/5.webp",
    detailUr2: "http://localhost:8001/photo/5_2.webp",
    detailUr3: "http://localhost:8001/photo/5_3.webp",
    detailUr4: "http://localhost:8001/photo/5_4.webp",
    shortTitle: "Titan",
    longTitle: "Analog Watch - For Men NP1773SL01",
    size: "32mm",
    mrp: 1151,
    cost: 2095,
    quantity: 1,
    description:
      "watch is a classic timekeeping device that displays the current time through traditional hour and minute hands on a circular dial.  ",
    discount: "45% OFF",
    tagline: "male",
  },
  {
    id: "product6",
    url: "http://localhost:8001/photo/6_1.webp",
    detailUrl: "http://localhost:8001/photo/6.webp",
    detailUr2: "http://localhost:8001/photo/6_2.webp",
    detailUr3: "http://localhost:8001/photo/6_3.webp",
    detailUr4: "http://localhost:8001/photo/6_4.webp",
    shortTitle: "Titan",
    longTitle: "Titan Analog Watch - For Men 1773SL04",
    size: "44mm",
    mrp: 1865,
    cost: 2195,
    quantity: 1,
    description:
      " It operates using precise mechanical or quartz movement, offering a timeless and elegant way to track time.  ",
    discount: "15% OFF",
    tagline: "male",
  },
  {
    id: "product7",
    url: "http://localhost:8001/photo/7_1.webp",
    detailUrl: "http://localhost:8001/photo/7.webp",
    detailUr2: "http://localhost:8001/photo/7_2.webp",
    detailUr3: "http://localhost:8001/photo/7_3.webp",
    detailUr4: "http://localhost:8001/photo/7_4.webp",
    shortTitle: "Titan",
    longTitle: "Analog Watch - For Men NP1773YL02",
    size: "36mm",
    mrp: 1108,
    cost: 2295,
    quantity: 1,
    description:
      "Analog watches come in various styles, materials, and designs, making them versatile accessories suitable for both formal and casual occasions. ",
    discount: "51% OFF",
    tagline: "male",
  },
  {
    id: "product8",
    url: "http://localhost:8001/photo/8_1.webp",
    detailUrl: "http://localhost:8001/photo/8.webp",
    detailUr2: "http://localhost:8001/photo/8_2.webp",
    detailUr3: "http://localhost:8001/photo/8_3.webp",
    detailUr4: "http://localhost:8001/photo/8_4.webp",
    shortTitle: "Titan",
    longTitle: "Neo Gents 2016 Analog Watch - For Men 1729SL02",
    size: "28mm",
    mrp: 992,
    cost: 1195,
    quantity: 1,
    description:
      " Titan analog watches come in various designs, materials, and colors, catering to a wide range of tastes and occasions. ",
    discount: "17% OFF",
    tagline: "male",
  },
  //fossil section
  {
    id: "product9",
    url: "http://localhost:8001/photo/9_1.webp",
    detailUrl: "http://localhost:8001/photo/9.webp",
    detailUr2: "http://localhost:8001/photo/9_2.webp",
    detailUr3: "http://localhost:8001/photo/9_3.webp",
    detailUr4: "http://localhost:8001/photo/9_4.webp",
    shortTitle: "Fossil",
    longTitle: "GRANT SPOR Analog Watch - For Men FS5268I",
    size: "36mm",
    mrp: 5621,
    cost: 12495,
    quantity: 1,
    description:
      " A Fossil watch is a stylish and contemporary timepiece known for its blend of fashion-forward design and reliable functionality.  ",
    discount: "55% OFF",
    tagline: "male",
  },
  {
    id: "product10",
    url: "http://localhost:8001/photo/10_1.webp",
    detailUrl: "http://localhost:8001/photo/10.webp",
    detailUr2: "http://localhost:8001/photo/10_2.webp",
    detailUr3: "http://localhost:8001/photo/10_3.webp",
    detailUr4: "http://localhost:8001/photo/10_4.webp",
    shortTitle: "Fossil",
    longTitle: "MACHINE Watch - For Men FS4662",
    size: "44mm",
    mrp: 6746,
    cost: 14995,
    quantity: 1,
    description:
      " Fossil watches often feature a distinctive combination of modern aesthetics and vintage-inspired elements, making them a popular choice among fashion-conscious individuals.  ",
    discount: "55% OFF",
    tagline: "male",
  },
  {
    id: "product11",
    url: "http://localhost:8001/photo/11_1.webp",
    detailUrl: "http://localhost:8001/photo/11.webp",
    detailUr2: "http://localhost:8001/photo/11_2.webp",
    detailUr3: "http://localhost:8001/photo/11_3.webp",
    detailUr4: "http://localhost:8001/photo/11_4.webp",
    shortTitle: "Fossil",
    longTitle: "NATE Analog Watch - For Men JR1354",
    size: "32mm",
    mrp: 8697,
    cost: 14495,
    quantity: 1,
    description:
      " These timepieces come in various styles, including chronographs, minimalist designs, and smartwatches, catering to a wide range of preferences. ",
    discount: "40% OFF",
    tagline: "male",
  },
  {
    id: "product12",
    url: "http://localhost:8001/photo/12.webp",
    detailUrl: "http://localhost:8001/photo/12.webp",
    detailUr2: "http://localhost:8001/photo/12_2.webp",
    detailUr3: "http://localhost:8001/photo/12_3.webp",
    detailUr4: "http://localhost:8001/photo/12_4.webp",
    shortTitle: "Fossil",
    longTitle: "NEUTRA CHRONO Analog Watch - For Men FS5381",
    size: "36mm",
    mrp: 4497,
    cost: 12495,
    quantity: 1,
    description:
      " Fossil watches are known for their quality craftsmanship, durable materials, and precise quartz movements, making them both fashionable accessories and reliable tools for keeping track of time.  ",
    discount: "40% OFF",
    tagline: "male",
  },
  //casio section
  {
    id: "product13",
    url: "http://localhost:8001/photo/13_1.webp",
    detailUrl: "http://localhost:8001/photo/13.webp",
    detailUr2: "http://localhost:8001/photo/13_2.webp",
    detailUr3: "http://localhost:8001/photo/13_3.webp",
    detailUr4: "http://localhost:8001/photo/13_4.webp",
    shortTitle: "Casio",
    longTitle: "Enticer Men's ( MTP-V005L-1BUDF ) Analog Watch - For Men A1489",
    size: "40mm",
    mrp: 878,
    cost: 2195,
    quantity: 1,
    description:
      " A Casio watch is a versatile and reliable timekeeping accessory that combines precision with affordability. ",
    discount: "60% OFF",
    tagline: "male",
  },
  {
    id: "product14",
    url: "http://localhost:8001/photo/14_1.webp",
    detailUrl: "http://localhost:8001/photo/14.webp",
    detailUr2: "http://localhost:8001/photo/14_2.webp",
    detailUr3: "http://localhost:8001/photo/14_3.webp",
    detailUr4: "http://localhost:8001/photo/14_4.webp",
    shortTitle: "Casio",
    longTitle: "ENTICER MEN Analog Watch - For Men A2036 (MTP-V005L-2B4UDF)",
    size: "28mm",
    mrp: 899,
    cost: 2195,
    quantity: 1,
    description:
      " Casio watches come in a variety of styles, including digital, analog-digital hybrids, and smartwatches.   ",
    discount: "59% OFF",
    tagline: "male",
  },
  {
    id: "product15",
    url: "http://localhost:8001/photo/15_1.webp",
    detailUrl: "http://localhost:8001/photo/15.webp",
    detailUr2: "http://localhost:8001/photo/15_2.webp",
    detailUr3: "http://localhost:8001/photo/15_3.webp",
    detailUr4: "http://localhost:8001/photo/15_4.webp",
    shortTitle: "Casio",
    longTitle: "ENTICER MEN Analog Watch - For Men A2038 (MTP-V005L-7B4UDF)",
    size: "44mm",
    mrp: 949,
    cost: 2195,
    quantity: 1,
    description:
      " These timepieces often feature features like water resistance, alarms, backlighting, and world time settings, making them suitable for everyday wear and outdoor activities.  ",
    discount: "56% OFF",
    tagline: "male",
  },
  {
    id: "product16",
    url: "http://localhost:8001/photo/16_1.webp",
    detailUrl: "http://localhost:8001/photo/16.webp",
    detailUr2: "http://localhost:8001/photo/16_2.webp",
    detailUr3: "http://localhost:8001/photo/16_3.webp",
    detailUr4: "http://localhost:8001/photo/16_4.webp",
    shortTitle: "Casio",
    longTitle: "Enticer ( MTP-1381L-7AVDF ) Analog Watch - For Men A845",
    size: "36mm",
    mrp: 1619,
    cost: 1499,
    quantity: 1,
    description:
      " Casio's commitment to quality and affordability has made their watches a popular choice for individuals seeking dependable timekeeping solutions.",
    discount: "28% OFF",
    tagline: "male",
  },
  // women

  {
    id: "product17",
    url: "http://localhost:8001/photo/17_1.webp",
    detailUrl: "http://localhost:8001/photo/17.webp",
    detailUr2: "http://localhost:8001/photo/17_2.webp",
    detailUr3: "http://localhost:8001/photo/17_3.webp",
    detailUr4: "http://localhost:8001/photo/17_4.webp",
    shortTitle: "Timex",
    longTitle: "Analog Watch - For Women TWEL155SMU01",
    size: "28mm",
    mrp: 1449,
    cost: 4250,
    quantity: 1,
    description:
      "A Timex watch is a timeless accessory that embodies simplicity, durability, and affordability. These watches are celebrated for their classic and versatile designs, making them suitable for various occasions and styles.  ",
    discount: "65% OFF",
    tagline: "women",
  },
  {
    id: "product18",
    url: "http://localhost:8001/photo/18_1.webp",
    detailUrl: "http://localhost:8001/photo/18.webp",
    detailUr2: "http://localhost:8001/photo/18_2.webp",
    detailUr3: "http://localhost:8001/photo/18_3.webp",
    detailUr4: "http://localhost:8001/photo/18_4.webp",
    shortTitle: "Timex",
    longTitle: "Analog Watch - For Women TWTL87SMU08",
    size: "32mm",
    mrp: 989,
    cost: 2495,
    quantity: 1,
    description:
      " Timex offers a wide range of options, including analog, digital, and hybrid models, with features like water resistance, Indiglo backlighting, and reliable quartz movements. ",
    discount: "60% OFF",
    tagline: "women",
  },
  {
    id: "product19",
    url: "http://localhost:8001/photo/19_1.webp",
    detailUrl: "http://localhost:8001/photo/19.webp",
    detailUr2: "http://localhost:8001/photo/19_2.webp",
    detailUr3: "http://localhost:8001/photo/19_3.webp",
    detailUr4: "http://localhost:8001/photo/19_4.webp",
    shortTitle: "Timex",
    longTitle: "Analog Watch - For Women TWTL10102",
    size: "36mm",
    mrp: 549,
    cost: 1299,
    quantity: 1,
    description:
      "With a commitment to craftsmanship and value, Timex watches have been a trusted choice for generations, providing accurate timekeeping and enduring style at accessible price points. ",
    discount: "57% OFF",
    tagline: "women",
  },
  {
    id: "product20",
    url: "http://localhost:8001/photo/20_1.webp",
    detailUrl: "http://localhost:8001/photo/20.webp",
    detailUr2: "http://localhost:8001/photo/20_2.webp",
    detailUr3: "http://localhost:8001/photo/20_3.webp",
    detailUr4: "http://localhost:8001/photo/20_4.webp",
    shortTitle: "Timex",
    longTitle: "Analog Watch - For Women TWTL10103",
    size: "28mm",
    mrp: 539,
    cost: 1299,
    quantity: 1,
    description:
      "A Timex watch is a classic and dependable timepiece known for its enduring quality and affordability. Timex has a long-standing reputation for creating watches that combine timeless design with practical functionality. ",
    discount: "58% OFF",
    tagline: "women",
  },

  {
    id: "product21",
    url: "http://localhost:8001/photo/21_1.webp",
    detailUrl: "http://localhost:8001/photo/21.webp",
    detailUr2: "http://localhost:8001/photo/21_2.webp",
    detailUr3: "http://localhost:8001/photo/21_3.webp",
    detailUr4: "http://localhost:8001/photo/21_4.webp",
    shortTitle: "Tommy Hilfiger",
    longTitle: "Analog Watch - For Women NCTH1781919",
    size: "40mm",
    mrp: 4050,
    cost: 6750,
    quantity: 1,
    description:
      "Tommy Hilfiger watches are renowned for their superior craftsmanship and use of high-quality materials.  ",
    discount: "40% OFF",
    tagline: "women",
  },
  {
    id: "product22",
    url: "http://localhost:8001/photo/22_1.webp",
    detailUrl: "http://localhost:8001/photo/22.webp",
    detailUr2: "http://localhost:8001/photo/22_2.webp",
    detailUr3: "http://localhost:8001/photo/22_3.webp",
    detailUr4: "http://localhost:8001/photo/22_4.webp",
    shortTitle: "Tommy Hilfiger",
    longTitle: "Analog Watch - For Women NCTH1782224",
    size: "44mm",
    mrp: 7972,
    cost: 16495,
    quantity: 1,
    description:
      "The stainless steel cases provide strength and longevity, while the precise quartz movements ensure accurate timekeeping.  ",
    discount: "51% OFF",
    tagline: "women",
  },
  {
    id: "product23",
    url: "http://localhost:8001/photo/23_1.webp",
    detailUrl: "http://localhost:8001/photo/23.webp",
    detailUr2: "http://localhost:8001/photo/23_2.webp",
    detailUr3: "http://localhost:8001/photo/23_3.webp",
    detailUr4: "http://localhost:8001/photo/23_4.webp",
    shortTitle: "Tommy Hilfiger",
    longTitle: "Cami Analog Watch - For Women TH1782377W",
    size: "40mm",
    mrp: 9604,
    cost: 13720,
    quantity: 1,
    description:
      "The attention to detail in every aspect, from the watch's construction to the choice of materials, is a testament to Tommy Hilfiger's commitment to excellence. ",
    discount: "30% OFF",
    tagline: "women",
  },
  {
    id: "product24",
    url: "http://localhost:8001/photo/24_1.webp",
    detailUrl: "http://localhost:8001/photo/24.webp",
    detailUr2: "http://localhost:8001/photo/24_2.webp",
    detailUr3: "http://localhost:8001/photo/24_3.webp",
    detailUr4: "http://localhost:8001/photo/24_4.webp",
    shortTitle: "Tommy Hilfiger",
    longTitle: "RACHEL Analog Watch - For Women TH1782552",
    size: "32mm",
    mrp: 9996,
    cost: 12495,
    quantity: 1,
    description:
      "This subtle yet distinctive branding adds character to the timepiece and makes it instantly recognizable as a Tommy Hilfiger creation. ",
    discount: "20% OFF",
    tagline: "women",
  },

  //Allen Solly

  {
    id: "product25",
    url: "http://localhost:8001/photo/25_1.webp",
    detailUrl: "http://localhost:8001/photo/25.webp",
    detailUr2: "http://localhost:8001/photo/25_2.webp",
    detailUr3: "http://localhost:8001/photo/25_3.webp",
    detailUr4: "http://localhost:8001/photo/25_4.webp",
    shortTitle: "Allen Solly",
    longTitle: "Analog Watch - For Women AS000015H",
    size: "36mm",
    mrp: 652,
    cost: 2174,
    quantity: 1,
    description:
      " Allen Solly watches are a fusion of contemporary style and sophistication. Crafted with attention to detail, these timepieces offer a versatile and modern accessory that complements various outfits.",
    discount: "70% OFF",
    tagline: "women",
  },
  {
    id: "product26",
    url: "http://localhost:8001/photo/26_1.webp",
    detailUrl: "http://localhost:8001/photo/26.webp",
    detailUr2: "http://localhost:8001/photo/26_2.webp",
    detailUr3: "http://localhost:8001/photo/26_3.webp",
    detailUr4: "http://localhost:8001/photo/26_4.webp",
    shortTitle: "Allen Solly",
    longTitle: "Analog Watch - For Women AS000015G",
    size: "28mm",
    mrp: 876,
    cost: 2922,
    quantity: 1,
    description:
      "Allen Solly typically uses a variety of materials in their watches, including stainless steel, leather straps, and mineral or sapphire crystal for the watch faces. ",
    discount: "20% OFF",
    tagline: "women",
  },
  {
    id: "product27",
    url: "http://localhost:8001/photo/27_1.webp",
    detailUrl: "http://localhost:8001/photo/27.webp",
    detailUr2: "http://localhost:8001/photo/27_2.webp",
    detailUr3: "http://localhost:8001/photo/27_3.webp",
    detailUr4: "http://localhost:8001/photo/27_4.webp",
    shortTitle: "Allen Solly",
    longTitle: "Analog Watch - For Women AS000043D",
    size: "36mm",
    mrp: 1181,
    cost: 4754,
    quantity: 1,
    description:
      " Higher-end models may use premium materials, such as Swiss movements and higher-quality leather.",
    discount: "75% OFF",
    tagline: "women",
  },
  {
    id: "product28",
    url: "http://localhost:8001/photo/28_1.webp",
    detailUrl: "http://localhost:8001/photo/28.webp",
    detailUr2: "http://localhost:8001/photo/28_2.webp",
    detailUr3: "http://localhost:8001/photo/28_3.webp",
    detailUr4: "http://localhost:8001/photo/28_4.webp",
    shortTitle: "Allen Solly",
    longTitle: "Analog Watch - For Women AS000030E",
    size: "40mm",
    mrp: 1239,
    cost: 5149,
    quantity: 1,
    description:
      " The quality of the movement (the internal mechanism that powers the watch) can greatly impact the watch's accuracy and longevity. .",
    discount: "75% OFF",
    tagline: "women",
  },
  //fossil section

  {
    id: "product29",
    url: "http://localhost:8001/photo/29_1.webp",
    detailUrl: "http://localhost:8001/photo/29.webp",
    detailUr2: "http://localhost:8001/photo/29_2.webp",
    detailUr3: "http://localhost:8001/photo/29_3.webp",
    detailUr4: "http://localhost:8001/photo/29_4.webp",
    shortTitle: "Fossil",
    longTitle: "acqueline Analog Watch - For Women ES5164",
    size: "44mm",
    mrp: 10146,
    cost: 14495,
    quantity: 1,
    description:
      "Fossil watches often use stainless steel for the case and bracelet, which is durable and resistant to corrosion. ",
    discount: "30% OFF",
    tagline: "women",
  },
  {
    id: "product30",
    url: "http://localhost:8001/photo/30_1.webp",
    detailUrl: "http://localhost:8001/photo/30.webp",
    detailUr2: "http://localhost:8001/photo/30_2.webp",
    detailUr3: "http://localhost:8001/photo/30_3.webp",
    detailUr4: "http://localhost:8001/photo/30_4.webp",
    shortTitle: "Fossil",
    longTitle: " FB-01 Analog Watch - For Women CE1111",
    size: "32mm",
    mrp: 4496,
    cost: 9995,
    quantity: 1,
    description:
      "They may also feature genuine leather straps for a classic look. The quality of materials can vary among different Fossil models, with higher-end models featuring premium materials.",
    discount: "55% OFF",
    tagline: "women",
  },
  {
    id: "product31",
    url: "http://localhost:8001/photo/31_1.webp",
    detailUrl: "http://localhost:8001/photo/31.webp",
    detailUr2: "http://localhost:8001/photo/31_2.webp",
    detailUr3: "http://localhost:8001/photo/31_3.webp",
    detailUr4: "http://localhost:8001/photo/31_4.webp",
    shortTitle: "Fossil",
    longTitle: "Izzy Analog Watch - For Women ES4888 ",
    size: "36mm",
    mrp: 4797,
    cost: 7995,
    quantity: 1,
    description:
      " Fossil watches typically use quartz movements, which are reliable and accurate. The specific movement may vary by model, but they are generally sourced from reputable manufacturers.",
    discount: "40% OFF",
    tagline: "women",
  },
  {
    id: "product32",
    url: "http://localhost:8001/photo/32_1.webp",
    detailUrl: "http://localhost:8001/photo/32.webp",
    detailUr2: "http://localhost:8001/photo/32_2.webp",
    detailUr3: "http://localhost:8001/photo/32_3.webp",
    detailUr4: "http://localhost:8001/photo/32_4.webp",
    shortTitle: "Fossil",
    longTitle: "Riley Analog Watch - For Women ES4519",
    size: "44mm",
    mrp: 5397,
    cost: 8995,
    quantity: 1,
    description:
      "Quality control and craftsmanship are generally good, with well-finished cases, clear and scratch-resistant crystals, and smooth operation of crowns and buttons. ",
    discount: "40% OFF",
    tagline: "women",
  },

  // children

  {
    id: "product33",
    url: "http://localhost:8001/photo/33.webp",
    detailUrl: "http://localhost:8001/photo/33.webp",
    detailUr2: "http://localhost:8001/photo/33_2.webp",
    detailUr3: "http://localhost:8001/photo/33_3.webp",
    detailUr4: "http://localhost:8001/photo/33_4.webp",
    shortTitle: "Noise",
    longTitle: "Noise ColorFit Caliber Smart Watch with 15-day battery, 1.69",
    size: "28mm",
    mrp: 999,
    cost: 3999,
    quantity: 1,
    description:
      "Noise Health SuiteTM: Body temperature sensor, Blood Oxygen, Heart rate monitor, Stress monitor and Sleep Monitor",
    discount: "75% OFF",
    tagline: "children",
  },
  {
    id: "product34",
    url: "http://localhost:8001/photo/34.webp",
    detailUrl: "http://localhost:8001/photo/34.webp",
    detailUr2: "http://localhost:8001/photo/34_2.webp",
    detailUr3: "http://localhost:8001/photo/34_3.webp",
    detailUr4: "http://localhost:8001/photo/34_4.webp",
    shortTitle: "Noise",
    longTitle:
      "Noise Icon 2 1.8'' Display with Bluetooth Calling, Women's Edition, AI Voice Assistant Smartwatch  (Pink Strap, Regular)",
    size: "32mm",
    mrp: 1599,
    cost: 5999,
    quantity: 1,
    description:
      "60 Sports mode & 100+ watch faces NoiseFit app: Pair with the improved Noisefit app for better health insights",
    discount: "73% OFF",
    tagline: "children",
  },

  {
    id: "product35",
    url: "http://localhost:8001/photo/35.webp",
    detailUrl: "http://localhost:8001/photo/35.webp",
    detailUr2: "http://localhost:8001/photo/35_2.webp",
    detailUr3: "http://localhost:8001/photo/35_3.webp",
    detailUr4: "http://localhost:8001/photo/35_4.webp",
    shortTitle: "Noise",
    longTitle:
      "Noise Loop 1.85'' Display with Advanced Bluetooth Calling, 550 Nits Brightness Smartwatch  (Black Strap, Regular)",
    size: "36mm",
    mrp: 1299,
    cost: 5999,
    quantity: 1,
    description: "children",
    discount: "78% OFF",
    tagline: "children",
  },

  {
    id: "product36",
    url: "http://localhost:8001/photo/36.webp",
    detailUrl: "http://localhost:8001/photo/36.webp",
    detailUr2: "http://localhost:8001/photo/36_2.webp",
    detailUr3: "http://localhost:8001/photo/36_3.webp",
    detailUr4: "http://localhost:8001/photo/36_4.webp",
    shortTitle: "Noise",
    longTitle: "1 Smartwatch, Magnetic Charger, User Manual, Warranty Card ",
    size: "40mm",
    mrp: 1431,
    cost: 2700,
    quantity: 1,
    description: "children",
    discount: "47% OFF",
    tagline: "children",
  },

  // Fire-Boltt

  {
    id: "product37",
    url: "http://localhost:8001/photo/37.webp",
    detailUrl: "http://localhost:8001/photo/37.webp",
    detailUr2: "http://localhost:8001/photo/37_2.webp",
    detailUr3: "http://localhost:8001/photo/37_3.webp",
    detailUr4: "http://localhost:8001/photo/37_4.webp",
    shortTitle: "Fire-Boltt",
    longTitle:
      "Fire-Boltt Ninja Pro Max Plus 1.83 Smartwatch  (Black Strap, Free Size)",
    size: "44mm",
    mrp: 999,
    cost: 7999,
    quantity: 1,
    description:
      "100 + Cloud Faces to match each style | All in One Social Update Notifications",
    discount: "87% OFF",
    tagline: "children",
  },
  {
    id: "product38",
    url: "http://localhost:8001/photo/38.webp",
    detailUrl: "http://localhost:8001/photo/38.webp",
    detailUr2: "http://localhost:8001/photo/38_2.webp",
    detailUr3: "http://localhost:8001/photo/38_3.webp",
    detailUr4: "http://localhost:8001/photo/38_4.webp",
    shortTitle: "Fire-Boltt",
    longTitle:
      "Fire-Boltt Ninja Calling Pro Plus 1.83 inch Display Smartwatch Bluetooth Calling, AI Voice Smartwatch  (Grey Strap, Free Size)",
    size: "36mm",
    mrp: 1499,
    cost: 9999,
    quantity: 1,
    description:
      "Bluetooth Calling Smartwatch - Make & Receive calls on the go through the watch  HD Display with 2.5D Curved Glass | 240*286 Pixel High Resolution",
    discount: "85% OFF",
    tagline: "children",
  },

  {
    id: "product39",
    url: "http://localhost:8001/photo/39.webp",
    detailUrl: "http://localhost:8001/photo/39.webp",
    detailUr2: "http://localhost:8001/photo/39_2.webp",
    detailUr3: "http://localhost:8001/photo/39_3.webp",
    detailUr4: "http://localhost:8001/photo/39_4.webp",
    shortTitle: "Fire-Boltt",
    longTitle: "Fire-Boltt Hurricane 1.3",
    size: "28mm",
    mrp: 1299,
    cost: 8999,
    quantity: 1,
    description:
      "2.5D Curved Glass for Best Retina HD Color Display with Automatic Motion Recognition",
    discount: "85% OFF",
    tagline: "children",
  },

  {
    id: "product40",
    url: "http://localhost:8001/photo/40.webp",
    detailUrl: "http://localhost:8001/photo/40.webp",
    detailUr2: "http://localhost:8001/photo/40_2.webp",
    detailUr3: "http://localhost:8001/photo/40_3.webp",
    detailUr4: "http://localhost:8001/photo/40_4.webp",
    shortTitle: "Fire-Boltt",
    longTitle: "Fire-Boltt Rise BT Calling,1.85",
    size: "32mm",
    mrp: 1499,
    cost: 11199,
    quantity: 1,
    description: "children",
    discount: "87% OFF",
    tagline:
      "123 Sports Modes to enhance those fitness goals | First Ever Neon UI & 8 UI interactions",
  },
  // boAt

  {
    id: "product41",
    url: "http://localhost:8001/photo/41.webp",
    detailUrl: "http://localhost:8001/photo/41.webp",
    detailUr2: "http://localhost:8001/photo/41_2.webp",
    detailUr3: "http://localhost:8001/photo/41_3.webp",
    detailUr4: "http://localhost:8001/photo/41_4.webp",
    shortTitle: "boAt",
    longTitle:
      "boAt Wave Beat Call with BT Calling,boAt Coins,DIY Watch Face Studio,1.69",
    size: "36mm",
    mrp: 1099,
    cost: 6499,
    quantity: 1,
    description:
      "The boAt Wave BeatCall is the next companion for your fitness transformation and is here to make life easy. Your Wave Style Call will remove all obstructions that may come on your goal achieving path. A large 1.69 Inches HD display makes everything come to life.",
    discount: "83% OFF",
    tagline: "children",
  },
  {
    id: "product42",
    url: "http://localhost:8001/photo/42.webp",
    detailUrl: "http://localhost:8001/photo/42.webp",
    detailUr2: "http://localhost:8001/photo/42_2.webp",
    detailUr3: "http://localhost:8001/photo/42_3.webp",
    detailUr4: "http://localhost:8001/photo/42_4.webp",
    shortTitle: "boAt",
    longTitle: "boAt Lunar Connect Ace with 1.43 ",
    size: "28mm",
    mrp: 1999,
    cost: 9499,
    quantity: 1,
    description:
      "he boAt Lunar Connect Ace is a perfect companion for your fitness transformation with a 3.63 cm (1.43) round dial AMOLED display and 100+ sports modes. ",
    discount: "78% OFF",
    tagline: "children",
  },

  {
    id: "product43",
    url: "http://localhost:8001/photo/43.webp",
    detailUrl: "http://localhost:8001/photo/43.webp",
    detailUr2: "http://localhost:8001/photo/43_2.webp",
    detailUr3: "http://localhost:8001/photo/43_3.webp",
    detailUr4: "http://localhost:8001/photo/43_4.webp",
    shortTitle: "boAt",
    longTitle:
      "boAt Lunar Mirage with 1.52 '' HD Display & Advanced Bluetooth Calling Smartwatch  (Metal Grey Strap, Free Size)",
    size: "44mm",
    mrp: 1699,
    cost: 8499,
    quantity: 1,
    description:
      "Seamlessly blending fashion with health, the Lunar Mirage offers Heart Rate & Blood Oxygen Monitoring for a holistic approach to well-being. Discover the future of smartwatch technology at your wrist.",
    discount: "80% OFF",
    tagline: "children",
  },

  {
    id: "product44",
    url: "http://localhost:8001/photo/44.webp",
    detailUrl: "http://localhost:8001/photo/44.webp",
    detailUr2: "http://localhost:8001/photo/44_2.webp",
    detailUr3: "http://localhost:8001/photo/44_3.webp",
    detailUr4: "http://localhost:8001/photo/44_4.webp",
    shortTitle: "boAt",
    longTitle: "boAt Ultima Prism with 1.96",
    size: "36mm",
    mrp: 2699,
    cost: 9499,
    quantity: 1,
    description:
      " just one tap, you can stay in touch with your loved ones thanks to the advanced Bluetooth calling feature. The watch not only acts as a fitness band but also keeps a track of your menstrual cycle No matter how sunny or cloudy the day is, nothing can stop you with IP67 dust.",
    discount: "71% OFF",
    tagline: "children",
  },

  //Fastrack
  {
    id: "product45",
    url: "http://localhost:8001/photo/45.webp",
    detailUrl: "http://localhost:8001/photo/45.webp",
    detailUr2: "http://localhost:8001/photo/45_2.webp",
    detailUr3: "http://localhost:8001/photo/45_3.webp",
    detailUr4: "http://localhost:8001/photo/45_4.webp",
    shortTitle: "Fastrack",
    longTitle:
      "Fastrack Revoltt FS1|1.83 Display|BT Calling|Fastcharge|110+ Sports Mode|200+ WatchFaces Smartwatch  (Black Strap, Free Size)",
    size: "32mm",
    mrp: 1499,
    cost: 3995,
    quantity: 1,
    description:
      "Advanced Chipset | SingleSync BT Calling |AI Voice Assistant, NitroFast Charge : 10 minutes = 1 day use |Upto 7 Days Battery",
    discount: "62% OFF",
    tagline: "children",
  },

  {
    id: "product46",
    url: "http://localhost:8001/photo/46.webp",
    detailUrl: "http://localhost:8001/photo/46.webp",
    detailUr2: "http://localhost:8001/photo/46_2.webp",
    detailUr3: "http://localhost:8001/photo/46_3.webp",
    detailUr4: "http://localhost:8001/photo/46_4.webp",
    shortTitle: "Fastrack",
    longTitle:
      "Fastrack FR1|1.39 inch Super UltraVU Display(360*360)|Advanced BT Calling|Split Screen Smartwatch  (Classic Black Strap, Free Size)",
    size: "28mm",
    mrp: 1699,
    cost: 5995,
    quantity: 1,
    description: "children",
    discount: "71% OFF",
    tagline: "children",
  },

  {
    id: "product47",
    url: "http://localhost:8001/photo/47.webp",
    detailUrl: "http://localhost:8001/photo/47.webp",
    detailUr2: "http://localhost:8001/photo/47_2.webp",
    detailUr3: "http://localhost:8001/photo/47_3.webp",
    detailUr4: "http://localhost:8001/photo/47_4.webp",
    shortTitle: "Fastrack",
    longTitle:
      "Fastrack Revoltt FR1 Pro|1.3Inch AMOLED display with 600 Nits|Advanced BT Calling Chipset Smartwatch  (Black Strap, Free Size)",
    size: "36mm",
    mrp: 2299,
    cost: 7995,
    quantity: 1,
    description:
      "Split Screen with Quick Feature Access for a Smooth and Rich Experience Connect with Fastrack Reflex World App|Seamless Customer Experience",
    discount: "71% OFF",
    tagline: "children",
  },

  {
    id: "product48",
    url: "http://localhost:8001/photo/48.webp",
    detailUrl: "http://localhost:8001/photo/48.webp",
    detailUr2: "http://localhost:8001/photo/48_2.webp",
    detailUr3: "http://localhost:8001/photo/48_3.webp",
    detailUr4: "http://localhost:8001/photo/48_4.webp",
    shortTitle: "Fastrack",
    longTitle:
      "Fastrack Revoltt FS1 Max|Biggest 1.95 UltraVU Curve Display|BT Calling|100+ Multisports Smartwatch  (Green Strap, Free Size)",
    size: "32mm",
    mrp: 1999,
    cost: 4995,
    quantity: 1,
    description:
      "Fastrack Revoltt FS1 Max comes with a large 1.95UltraVU Curve Display and is ready to style your wrist with a bright pixel resolution and brand-new amazing colours",
    discount: "59% OFF",
    tagline: "children",
  },
];
